{
 "title": "Dummy dash",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Topic out bytes/min ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_bytes_out_per_minute",
     "legendFormat": "Input"
    }
   ]
  },
  {
   "title": "Producer delay to generate a time in sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "producer_sleep_time", "legendFormat": "Dely" }
   ]
  },
  {
   "title": "Kafka Topic in bytes/min ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_bytes_in_per_minute{topic='input'}",
     "legendFormat": "Input"
    },
    {
     "expr": "kafka_server_bytes_in_per_minute{topic=\"output\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Converted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consumer_convert_total" }
   ]
  }
 ]
}